program BiosferaR;

uses
  Forms,
  Bio.BaseObject in '..\source\bio\Bio.BaseObject.pas',
  Bio.Bird in '..\source\bio\Bio.Bird.pas',
  Bio.Bot in '..\source\bio\Bio.Bot.pas',
  Bio.Coordinates in '..\source\bio\Bio.Coordinates.pas',
  Bio.Crab in '..\source\bio\Bio.Crab.pas',
  Bio.Creature in '..\source\bio\Bio.Creature.pas',
  Bio.Environment in '..\source\bio\Bio.Environment.pas',
  Bio.EnvironmentStructures in '..\source\bio\Bio.EnvironmentStructures.pas',
  Bio.Explosions in '..\source\bio\Bio.Explosions.pas',
  Bio.Fish in '..\source\bio\Bio.Fish.pas',
  Bio.Force in '..\source\bio\Bio.Force.pas',
  Bio.Fox in '..\source\bio\Bio.Fox.pas',
  Bio.Grass in '..\source\bio\Bio.Grass.pas',
  Bio.Grazer in '..\source\bio\Bio.Grazer.pas',
  Bio.Grid in '..\source\bio\Bio.Grid.pas',
  Bio.Hawk in '..\source\bio\Bio.Hawk.pas',
  Bio.Life in '..\source\bio\Bio.Life.pas',
  Bio.Link in '..\source\bio\Bio.Link.pas',
  Bio.Position in '..\source\bio\Bio.Position.pas',
  Bio.Rabbit in '..\source\bio\Bio.Rabbit.pas',
  Bio.Reality in '..\source\bio\Bio.Reality.pas',
  Bio.Satellites in '..\source\bio\Bio.Satellites.pas',
  Bio.Shark in '..\source\bio\Bio.Shark.pas',
  Bio.Space in '..\source\bio\Bio.Space.pas',
  Bio.Terrier in '..\source\bio\Bio.Terrier.pas',
  Bio.ThingReferenceList in '..\source\bio\Bio.ThingReferenceList.pas',
  Bio.Tool in '..\source\bio\Bio.Tool.pas',
  Bio.Trees in '..\source\bio\Bio.Trees.pas',
  Bio.Trex in '..\source\bio\Bio.Trex.pas',
  Bio.Turtle in '..\source\bio\Bio.Turtle.pas',
  Bio.Vibes in '..\source\bio\Bio.Vibes.pas',
  Bio.Weather in '..\source\bio\Bio.Weather.pas',
  Bio.Globals in '..\source\bio\Bio.Globals.pas',
  Bio.UserSettings in '..\source\bio\Bio.UserSettings.pas',
  Bio.Mouse in '..\source\bio\Bio.Mouse.pas',
  Bio.Tiger in '..\source\bio\Bio.Tiger.pas',
  Bio.Duck in '..\source\bio\Bio.Duck.pas',
  Bio.Community in '..\source\bio\Bio.Community.pas',
  Bio.Mating in '..\source\bio\Bio.Mating.pas',
  Bio.Dolphin in '..\source\bio\Bio.Dolphin.pas',
  Bio.ReportCard in '..\source\bio\Bio.ReportCard.pas',
  Bio.Ladybug in '..\source\bio\Bio.Ladybug.pas',
  Bio.Ant in '..\source\bio\Bio.Ant.pas',
  Bio.LearningCreature in '..\source\bio\Bio.LearningCreature.pas',
  Bio.DNA in '..\source\bio\Bio.DNA.pas',
  Bio.GeneticCreature in '..\source\bio\Bio.GeneticCreature.pas',
  Bio.EvolvingTrees in '..\source\bio\Bio.EvolvingTrees.pas',
  Bio.MatingSingle in '..\source\bio\Bio.MatingSingle.pas',
  Bio.FireTree in '..\source\bio\Bio.FireTree.pas',
  Bio.MissileDefence in '..\source\bio\Bio.MissileDefence.pas',
  fbAboutR in '..\source\bio\fbAboutR.pas' {FormAbout},
  fbConstructionR in '..\source\bio\fbConstructionR.pas' {fmConstruction},
  fbCreatingGalaxyR in '..\source\bio\fbCreatingGalaxyR.pas' {FormCreatingGalaxy},
  fbEditLineR in '..\source\bio\fbEditLineR.pas' {FormEditLine},
  fbEventsR in '..\source\bio\fbEventsR.pas' {FormEvents},
  fbIntroR in '..\source\bio\fbIntroR.pas' {FormIntro},
  fbKeyboardR in '..\source\bio\fbKeyboardR.pas' {FormKeyboard},
  fbListsR in '..\source\bio\fbListsR.pas' {fmLists},
  fbManagerR in '..\source\bio\fbManagerR.pas' {FormManager},
  fbMaximumsR in '..\source\bio\fbMaximumsR.pas' {FormMaximums},
  fbNewRealityR in '..\source\bio\fbNewRealityR.pas' {FormNewReality},
  fbPhotographR in '..\source\bio\fbPhotographR.pas' {FormPhotograph},
  fbRealityR in '..\source\bio\fbRealityR.pas' {fmReality},
  fbSatelliteR in '..\source\bio\fbSatelliteR.pas' {FormSatellite},
  fbSettingsR in '..\source\bio\fbSettingsR.pas' {FormSettings},
  fbSpiritR in '..\source\bio\fbSpiritR.pas' {FormSpirit},
  vInterfaceClasses in '..\source\bio\vInterfaceClasses.pas',
  fbFirstFormR in '..\source\bio\fbFirstFormR.pas' {frmFirst},
  vSpiritManagerR in '..\source\bio\vSpiritManagerR.pas',
  vSplashScreen in '..\source\bio\vSplashScreen.pas',
  fbPopulationsR in '..\source\bio\fbPopulationsR.pas' {FormPopulations},
  fbHeightFieldR in '..\source\bio\fbHeightFieldR.pas' {FormHeightField},
  fbHumidityMapR in '..\source\bio\fbHumidityMapR.pas' {FormHumidityMap},
  fbPositionR in '..\source\bio\fbPositionR.pas' {FormPosition},
  fbDNAR in '..\source\bio\fbDNAR.pas' {FormDNA},
  fbErrorR in '..\source\bio\fbErrorR.pas' {FormError},
  fbTipR in '..\source\bio\fbTipR.pas' {FormTip},
  fbSplashR in '..\source\bio\fbSplashR.pas' {fmSplash},
  fbImagesR in '..\source\bio\fbImagesR.pas' {FormImages},
  Bio.Things in '..\source\bio\Bio.Things.pas',
  Bio.Utilities in '..\source\bio\Bio.Utilities.pas',
  fbTutorialR in '..\source\bio\fbTutorialR.pas' {fmTutorial},
  dbImages in '..\source\bio\dbImages.pas' {DataModuleImages: TDataModule},
  fbMiniFormR in '..\source\bio\fbMiniFormR.pas',
  Space.Globals in '..\source\Space.Globals.pas',
  fbBiosferaR in '..\source\bio\fbBiosferaR.pas' {FormBiosfera};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'BioSphere';
  Application.CreateForm(TfrmFirst, frmFirst);
  Application.CreateForm(TfmSplash, fmSplash);
  Application.CreateForm(TFormImages, FormImages);
  Application.Run;
end.
