program Biosfera_ru;

uses
  Forms,
  Bio.BaseObject in '..\source\bio\Bio.BaseObject.pas',
  Bio.Bird in '..\source\bio\Bio.Bird.pas',
  Bio.Bot in '..\source\bio\Bio.Bot.pas',
  Bio.Coordinates in '..\source\bio\Bio.Coordinates.pas',
  Bio.Crab in '..\source\bio\Bio.Crab.pas',
  Bio.Creature in '..\source\bio\Bio.Creature.pas',
  Bio.Environment in '..\source\bio\Bio.Environment.pas',
  Bio.EnvironmentStructures in '..\source\bio\Bio.EnvironmentStructures.pas',
  Bio.Explosions in '..\source\bio\Bio.Explosions.pas',
  Bio.Fish in '..\source\bio\Bio.Fish.pas',
  Bio.Force in '..\source\bio\Bio.Force.pas',
  Bio.Fox in '..\source\bio\Bio.Fox.pas',
  Bio.Grass in '..\source\bio\Bio.Grass.pas',
  Bio.Grazer in '..\source\bio\Bio.Grazer.pas',
  Bio.Grid in '..\source\bio\Bio.Grid.pas',
  Bio.Hawk in '..\source\bio\Bio.Hawk.pas',
  Bio.Life in '..\source\bio\Bio.Life.pas',
  Bio.Link in '..\source\bio\Bio.Link.pas',
  Bio.Position in '..\source\bio\Bio.Position.pas',
  Bio.Rabbit in '..\source\bio\Bio.Rabbit.pas',
  Bio.Reality in '..\source\bio\Bio.Reality.pas',
  Bio.Satellites in '..\source\bio\Bio.Satellites.pas',
  Bio.Shark in '..\source\bio\Bio.Shark.pas',
  Bio.Space in '..\source\bio\Bio.Space.pas',
  Bio.Terrier in '..\source\bio\Bio.Terrier.pas',
  Bio.ThingReferenceList in '..\source\bio\Bio.ThingReferenceList.pas',
  Bio.Tool in '..\source\bio\Bio.Tool.pas',
  Bio.Trees in '..\source\bio\Bio.Trees.pas',
  Bio.Trex in '..\source\bio\Bio.Trex.pas',
  Bio.Turtle in '..\source\bio\Bio.Turtle.pas',
  Bio.Vibes in '..\source\bio\Bio.Vibes.pas',
  Bio.Weather in '..\source\bio\Bio.Weather.pas',
  Bio.Globals in '..\source\bio\Bio.Globals.pas',
  Bio.UserSettings in '..\source\bio\Bio.UserSettings.pas',
  Bio.Mouse in '..\source\bio\Bio.Mouse.pas',
  Bio.Tiger in '..\source\bio\Bio.Tiger.pas',
  Bio.Duck in '..\source\bio\Bio.Duck.pas',
  Bio.Community in '..\source\bio\Bio.Community.pas',
  Bio.Mating in '..\source\bio\Bio.Mating.pas',
  Bio.Dolphin in '..\source\bio\Bio.Dolphin.pas',
  Bio.ReportCard in '..\source\bio\Bio.ReportCard.pas',
  Bio.Ladybug in '..\source\bio\Bio.Ladybug.pas',
  Bio.Ant in '..\source\bio\Bio.Ant.pas',
  Bio.LearningCreature in '..\source\bio\Bio.LearningCreature.pas',
  Bio.DNA in '..\source\bio\Bio.DNA.pas',
  Bio.GeneticCreature in '..\source\bio\Bio.GeneticCreature.pas',
  Bio.EvolvingTrees in '..\source\bio\Bio.EvolvingTrees.pas',
  Bio.MatingSingle in '..\source\bio\Bio.MatingSingle.pas',
  Bio.FireTree in '..\source\bio\Bio.FireTree.pas',
  Bio.MissileDefence in '..\source\bio\Bio.MissileDefence.pas',
  fbAbout_ru in '..\source\bio\fbAbout_ru.pas' {FormAbout},
  fbConstruction_ru in '..\source\bio\fbConstruction_ru.pas' {frmConstruction},
  fbCreatingGalaxy_ru in '..\source\bio\fbCreatingGalaxy_ru.pas' {FormCreatingGalaxy},
  fbEditLine_ru in '..\source\bio\fbEditLine_ru.pas' {FormEditLine},
  fbEvents_ru in '..\source\bio\fbEvents_ru.pas' {FormEvents},
  fbIntro_ru in '..\source\bio\fbIntro_ru.pas' {FormIntro},
  fbKeyboard_ru in '..\source\bio\fbKeyboard_ru.pas' {FormKeyboard},
  fbLists_ru in '..\source\bio\fbLists_ru.pas' {frmLists},
  fbManager_ru in '..\source\bio\fbManager_ru.pas' {FormManager},
  fbMaximums_ru in '..\source\bio\fbMaximums_ru.pas' {FormMaximums},
  fbNewReality_ru in '..\source\bio\fbNewReality_ru.pas' {FormNewReality},
  fbPhotograph_ru in '..\source\bio\fbPhotograph_ru.pas' {FormPhotograph},
  fbReality_ru in '..\source\bio\fbReality_ru.pas' {FormReality},
  fbSatellite_ru in '..\source\bio\fbSatellite_ru.pas' {FormSatellite},
  fbSettings_ru in '..\source\bio\fbSettings_ru.pas' {FormSettings},
  fbSpirit_ru in '..\source\bio\fbSpirit_ru.pas' {FormSpirit},
  vInterfaceClasses in '..\source\bio\vInterfaceClasses.pas',
  fbFirstForm_ru in '..\source\bio\fbFirstForm_ru.pas' {frmFirst},
  vSplashScreen in '..\source\bio\vSplashScreen.pas',
  fbPopulations_ru in '..\source\bio\fbPopulations_ru.pas' {FormPopulations},
  fbHeightField_ru in '..\source\bio\fbHeightField_ru.pas' {FormHeightField},
  fbHumidityMap_ru in '..\source\bio\fbHumidityMap_ru.pas' {FormHumidityMap},
  fbPosition_ru in '..\source\bio\fbPosition_ru.pas' {FormPosition},
  fbDNAR in '..\source\bio\fbDNAR.pas' {FormDNA},
  fbError_ru in '..\source\bio\fbError_ru.pas' {FormError},
  fbTip_ru in '..\source\bio\fbTip_ru.pas' {FormTip},
  fbSplash_ru in '..\source\bio\fbSplash_ru.pas' {FormSplash},
  fbImages_ru in '..\source\bio\fbImages_ru.pas' {frmImages},
  Bio.Things in '..\source\bio\Bio.Things.pas',
  Bio.Utilities in '..\source\bio\Bio.Utilities.pas',
  fbTutorial_ru in '..\source\bio\fbTutorial_ru.pas' {FormTutorial},
  dbImages in '..\source\bio\dbImages.pas' {DataModuleImages: TDataModule},
  fbMiniForm_ru in '..\source\bio\fbMiniForm_ru.pas',
  Space.Globals in '..\source\Space.Globals.pas',
  fbBiosfera_ru in '..\source\bio\fbBiosfera_ru.pas' {FormBiosfera},
  vSpiritManager_ru in '..\source\bio\vSpiritManager_ru.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Biosfera';
  Application.CreateForm(TfrmFirst, frmFirst);
  Application.CreateForm(TfrmLists, frmLists);
  Application.CreateForm(TfrmConstruction, frmConstruction);
  Application.CreateForm(TfrmImages, frmImages);
  Application.CreateForm(TDataModuleImages, DataModuleImages);
  Application.Run;
end.
