program Biosfera;

uses
  Forms,
  Bio.BaseObject in 'source\bio\Bio.BaseObject.pas',
  Bio.Bird in 'source\bio\Bio.Bird.pas',
  Bio.Bot in 'source\bio\Bio.Bot.pas',
  Bio.Coordinates in 'source\bio\Bio.Coordinates.pas',
  Bio.Crab in 'source\bio\Bio.Crab.pas',
  Bio.Creature in 'source\bio\Bio.Creature.pas',
  Bio.Environment in 'source\bio\Bio.Environment.pas',
  Bio.EnvironmentStructures in 'source\bio\Bio.EnvironmentStructures.pas',
  Bio.Explosions in 'source\bio\Bio.Explosions.pas',
  Bio.Fish in 'source\bio\Bio.Fish.pas',
  Bio.Force in 'source\bio\Bio.Force.pas',
  Bio.Fox in 'source\bio\Bio.Fox.pas',
  Bio.Grass in 'source\bio\Bio.Grass.pas',
  Bio.Grazer in 'source\bio\Bio.Grazer.pas',
  Bio.Grid in 'source\bio\Bio.Grid.pas',
  Bio.Hawk in 'source\bio\Bio.Hawk.pas',
  Bio.Life in 'source\bio\Bio.Life.pas',
  Bio.Link in 'source\bio\Bio.Link.pas',
  Bio.Position in 'source\bio\Bio.Position.pas',
  Bio.Rabbit in 'source\bio\Bio.Rabbit.pas',
  Bio.Reality in 'source\bio\Bio.Reality.pas',
  Bio.Satellites in 'source\bio\Bio.Satellites.pas',
  Bio.Shark in 'source\bio\Bio.Shark.pas',
  Bio.Space in 'source\bio\Bio.Space.pas',
  Bio.Terrier in 'source\bio\Bio.Terrier.pas',
  Bio.ThingReferenceList in 'source\bio\Bio.ThingReferenceList.pas',
  Bio.Tool in 'source\bio\Bio.Tool.pas',
  Bio.Trees in 'source\bio\Bio.Trees.pas',
  Bio.Trex in 'source\bio\Bio.Trex.pas',
  Bio.Turtle in 'source\bio\Bio.Turtle.pas',
  Bio.Vibes in 'source\bio\Bio.Vibes.pas',
  Bio.Weather in 'source\bio\Bio.Weather.pas',
  Bio.Globals in 'source\bio\Bio.Globals.pas',
  Bio.UserSettings in 'source\bio\Bio.UserSettings.pas',
  Bio.Mouse in 'source\bio\Bio.Mouse.pas',
  Bio.Tiger in 'source\bio\Bio.Tiger.pas',
  Bio.Duck in 'source\bio\Bio.Duck.pas',
  Bio.Community in 'source\bio\Bio.Community.pas',
  Bio.Mating in 'source\bio\Bio.Mating.pas',
  Bio.Dolphin in 'source\bio\Bio.Dolphin.pas',
  Bio.ReportCard in 'source\bio\Bio.ReportCard.pas',
  Bio.Ladybug in 'source\bio\Bio.Ladybug.pas',
  Bio.Ant in 'source\bio\Bio.Ant.pas',
  Bio.LearningCreature in 'source\bio\Bio.LearningCreature.pas',
  Bio.DNA in 'source\bio\Bio.DNA.pas',
  Bio.GeneticCreature in 'source\bio\Bio.GeneticCreature.pas',
  Bio.EvolvingTrees in 'source\bio\Bio.EvolvingTrees.pas',
  Bio.MatingSingle in 'source\bio\Bio.MatingSingle.pas',
  Bio.FireTree in 'source\bio\Bio.FireTree.pas',
  Bio.MissileDefence in 'source\bio\Bio.MissileDefence.pas',
  fbBiosfera in 'source\bio\fbBiosfera.pas' {FormBiosfera},
  fbAbout in 'source\bio\fbAbout.pas' {FormAbout},
  fbConstruction in 'source\bio\fbConstruction.pas' {fmConstruction},
  fbCreatingGalaxy in 'source\bio\fbCreatingGalaxy.pas' {FormCreatingGalaxy},
  fbEditLine in 'source\bio\fbEditLine.pas' {FormEditLine},
  fbEvents in 'source\bio\fbEvents.pas' {FormEvents},
  fbIntro in 'source\bio\fbIntro.pas' {FormIntro},
  fbKeyboard in 'source\bio\fbKeyboard.pas' {FormKeyboard},
  fbLists in 'source\bio\fbLists.pas' {fmLists},
  fbManager in 'source\bio\fbManager.pas' {FormManager},
  fbMaximums in 'source\bio\fbMaximums.pas' {FormMaximums},
  fbNewReality in 'source\bio\fbNewReality.pas' {FormNewReality},
  fbPhotograph in 'source\bio\fbPhotograph.pas' {FormPhotograph},
  fbReality in 'source\bio\fbReality.pas' {fmReality},
  fbSatellite in 'source\bio\fbSatellite.pas' {FormSatellite},
  fbSettings in 'source\bio\fbSettings.pas' {FormSettings},
  fbSpirit in 'source\bio\fbSpirit.pas' {FormSpirit},
  fbTutorial in 'source\bio\fbTutorial.pas',
  vInterfaceClasses in 'source\bio\vInterfaceClasses.pas',
  fbFirstForm in 'source\bio\fbFirstForm.pas' {FormFirst},
  vSpiritManager in 'source\bio\vSpiritManager.pas',
  vSplashScreen in 'source\bio\vSplashScreen.pas',
  fbPopulations in 'source\bio\fbPopulations.pas' {FormPopulations},
  fbHeightField in 'source\bio\fbHeightField.pas' {FormHeightField},
  fbHumidityMap in 'source\bio\fbHumidityMap.pas' {FormHumidityMap},
  fbPosition in 'source\bio\fbPosition.pas' {FormPosition},
  fbDNA in 'source\bio\fbDNA.pas' {FormDNA},
  fbError in 'source\bio\fbError.pas' {FormError},
  fbTip in 'source\bio\fbTip.pas' {FormTip},
  fbSplash in 'source\bio\fbSplash.pas' {fmSplash},
  fbMiniForm in 'source\bio\fbMiniForm.pas',
  fbImages in 'source\bio\fbImages.pas' {FormImages},
  Bio.Things in 'source\bio\Bio.Things.pas',
  Bio.Utilities in 'source\bio\Bio.Utilities.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'BioSphere';
  Application.CreateForm(TFormFirst, FormFirst);
  Application.CreateForm(TfmSplash, fmSplash);
  Application.CreateForm(TFormImages, FormImages);
  Application.Run;
end.
