program Bioneta_en;

uses
  Forms,
  Bio.BaseObject in '..\source\bio\Bio.BaseObject.pas',
  Bio.Birds in '..\source\bio\Bio.Birds.pas',
  Bio.Bot in '..\source\bio\Bio.Bot.pas',
  Bio.Coordinates in '..\source\bio\Bio.Coordinates.pas',
  Bio.Crab in '..\source\bio\Bio.Crab.pas',
  Bio.Creature in '..\source\bio\Bio.Creature.pas',
  Bio.Environment in '..\source\bio\Bio.Environment.pas',
  Bio.EnvironmentStructures in '..\source\bio\Bio.EnvironmentStructures.pas',
  Bio.Explosions in '..\source\bio\Bio.Explosions.pas',
  Bio.Pisces in '..\source\bio\Bio.Pisces.pas',
  Bio.Force in '..\source\bio\Bio.Force.pas',
  Bio.Fox in '..\source\bio\Bio.Fox.pas',
  Bio.Grazer in '..\source\bio\Bio.Grazer.pas',
  Bio.Grid in '..\source\bio\Bio.Grid.pas',
  Bio.Life in '..\source\bio\Bio.Life.pas',
  Bio.Link in '..\source\bio\Bio.Link.pas',
  Bio.Position in '..\source\bio\Bio.Position.pas',
  Bio.Rabbit in '..\source\bio\Bio.Rabbit.pas',
  Bio.Reality in '..\source\bio\Bio.Reality.pas',
  Bio.Satellites in '..\source\bio\Bio.Satellites.pas',
  Bio.Space in '..\source\bio\Bio.Space.pas',
  Bio.Terrier in '..\source\bio\Bio.Terrier.pas',
  Bio.ThingReferenceList in '..\source\bio\Bio.ThingReferenceList.pas',
  Bio.Tool in '..\source\bio\Bio.Tool.pas',
  Bio.Flora in '..\source\bio\Bio.Flora.pas',
  Bio.Trex in '..\source\bio\Bio.Trex.pas',
  Bio.Turtle in '..\source\bio\Bio.Turtle.pas',
  Bio.Vibes in '..\source\bio\Bio.Vibes.pas',
  Bio.Weather in '..\source\bio\Bio.Weather.pas',
  Bio.Globals in '..\source\bio\Bio.Globals.pas',
  Bio.UserSettings in '..\source\bio\Bio.UserSettings.pas',
  Bio.Mouse in '..\source\bio\Bio.Mouse.pas',
  Bio.Tiger in '..\source\bio\Bio.Tiger.pas',
  Bio.Community in '..\source\bio\Bio.Community.pas',
  Bio.Mating in '..\source\bio\Bio.Mating.pas',
  Bio.Dolphin in '..\source\bio\Bio.Dolphin.pas',
  Bio.ReportCard in '..\source\bio\Bio.ReportCard.pas',
  Bio.Insects in '..\source\bio\Bio.Insects.pas',
  Bio.LearningCreature in '..\source\bio\Bio.LearningCreature.pas',
  Bio.DNA in '..\source\bio\Bio.DNA.pas',
  Bio.GeneticCreature in '..\source\bio\Bio.GeneticCreature.pas',
  Bio.EvolvingTrees in '..\source\bio\Bio.EvolvingTrees.pas',
  Bio.MatingSingle in '..\source\bio\Bio.MatingSingle.pas',
  Bio.FireTree in '..\source\bio\Bio.FireTree.pas',
  Bio.MissileDefence in '..\source\bio\Bio.MissileDefence.pas',
  fbBioneta_en in '..\source\bio\en\fbBioneta_en.pas' {FormBioneta},
  fbAbout_en in '..\source\bio\en\fbAbout_en.pas' {FormAbout},
  fbConstruction_en in '..\source\bio\en\fbConstruction_en.pas' {FormConstruction},
  fbCreatingGalaxy_en in '..\source\bio\en\fbCreatingGalaxy_en.pas' {FormCreatingGalaxy},
  fbEditLine_en in '..\source\bio\en\fbEditLine_en.pas' {FormEditLine},
  fbEvents_en in '..\source\bio\en\fbEvents_en.pas' {FormEvents},
  fbIntro_en in '..\source\bio\en\fbIntro_en.pas' {FormIntro},
  fbKeyboard_en in '..\source\bio\en\fbKeyboard_en.pas' {FormKeyboard},
  fbLists_en in '..\source\bio\en\fbLists_en.pas' {FormLists},
  fbManager_en in '..\source\bio\en\fbManager_en.pas' {FormManager},
  fbMaximums_en in '..\source\bio\en\fbMaximums_en.pas' {FormMaximums},
  fbNewReality_en in '..\source\bio\en\fbNewReality_en.pas' {FormNewReality},
  fbPhotograph_en in '..\source\bio\en\fbPhotograph_en.pas' {FormPhotograph},
  fbReality_en in '..\source\bio\en\fbReality_en.pas' {FormReality},
  fbSatellite_en in '..\source\bio\en\fbSatellite_en.pas' {FormSatellite},
  fbOptions_en in '..\source\bio\en\fbOptions_en.pas' {FormOptions},
  fbSpirit_en in '..\source\bio\en\fbSpirit_en.pas' {FormSpirit},
  vInterfaceClasses in '..\source\bio\vInterfaceClasses.pas',
  fbFirstForm_en in '..\source\bio\en\fbFirstForm_en.pas' {FormFirst},
  vSpiritManager_en in '..\source\bio\en\vSpiritManager_en.pas',
  vSplashScreen in '..\source\bio\vSplashScreen.pas',
  fbPopulations_en in '..\source\bio\en\fbPopulations_en.pas' {FormPopulations},
  fbHeightField_en in '..\source\bio\en\fbHeightField_en.pas' {FormHeightField},
  fbHumidityMap_en in '..\source\bio\en\fbHumidityMap_en.pas' {FormHumidityMap},
  fbPosition_en in '..\source\bio\en\fbPosition_en.pas' {FormPosition},
  fbDNA_en in '..\source\bio\en\fbDNA_en.pas' {FormDNA},
  fbError_en in '..\source\bio\en\fbError_en.pas' {FormError},
  fbTip_en in '..\source\bio\en\fbTip_en.pas' {FormTip},
  fbSplash_en in '..\source\bio\en\fbSplash_en.pas' {FormSplash},
  fbImages_en in '..\source\bio\en\fbImages_en.pas' {frmImages},
  Bio.Things in '..\source\bio\Bio.Things.pas',
  Bio.Utilities in '..\source\bio\Bio.Utilities.pas',
  fbTutorial_en in '..\source\bio\en\fbTutorial_en.pas' {FormTutorial},
  fbMiniForm_en in '..\source\bio\en\fbMiniForm_en.pas',
  Astro.Globals in '..\source\astro\Astro.Globals.pas',
  dbImages in '..\source\bio\dbImages.pas' {DataModuleImages: TDataModule};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Bioneta';
  Application.CreateForm(TFormFirst, FormFirst);
  Application.CreateForm(TfrmImages, frmImages);
  Application.CreateForm(TFormConstruction, FormConstruction);
  Application.CreateForm(TFormLists, FormLists);
  Application.CreateForm(TDataModuleImages, DataModuleImages);
  Application.Run;
end.
