object FormGridOptions: TFormGridOptions
  Left = 0
  Top = 0
  Margins.Left = 5
  Margins.Top = 5
  Margins.Right = 5
  Margins.Bottom = 5
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  ClientHeight = 614
  ClientWidth = 574
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -19
  Font.Name = 'Tahoma'
  Font.Style = []
  PixelsPerInch = 168
  DesignSize = (
    574
    614)
  TextHeight = 23
  object GroupBoxXY: TGroupBox
    Left = 7
    Top = 4
    Width = 546
    Height = 141
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Anchors = [akTop, akRight]
    Caption = '  X, Y '#1088#1072#1084#1082#1080' '#1075#1088#1080#1076#1072
    ParentShowHint = False
    ShowHint = True
    TabOrder = 0
    object Label7: TLabel
      Left = 72
      Top = 26
      Width = 81
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = #1052#1080#1085#1080#1084#1091#1084
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label8: TLabel
      Left = 186
      Top = 26
      Width = 87
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = #1052#1072#1082#1089#1080#1084#1091#1084
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label9: TLabel
      Left = 291
      Top = 26
      Width = 96
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Alignment = taRightJustify
      Caption = #1048#1085#1082#1088#1077#1084#1077#1085#1090
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label11: TLabel
      Left = -4
      Top = 54
      Width = 36
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'x :'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label12: TLabel
      Left = -4
      Top = 93
      Width = 36
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'y :'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label10: TLabel
      Left = 424
      Top = 26
      Width = 115
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = #1055#1086#1079#1080#1094#1080#1103' ( z )'
    end
    object EditxyGridMinx: TEdit
      Left = 37
      Top = 51
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      OnChange = EditxyGridMinxChange
      OnKeyPress = FloatKeyPress
    end
    object EditxyGridMaxx: TEdit
      Left = 161
      Top = 51
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      OnChange = EditxyGridMaxxChange
      OnKeyPress = FloatKeyPress
    end
    object EditxyGridStpx: TEdit
      Left = 287
      Top = 51
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      OnChange = EditxyGridStpxChange
      OnKeyPress = PositiveKeyPress
    end
    object EditxyGridMiny: TEdit
      Left = 37
      Top = 89
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      OnChange = EditxyGridMinyChange
      OnKeyPress = FloatKeyPress
    end
    object EditxyGridMaxy: TEdit
      Left = 161
      Top = 89
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      OnChange = EditxyGridMaxyChange
      OnKeyPress = FloatKeyPress
    end
    object EditxyGridStpy: TEdit
      Left = 287
      Top = 89
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
      OnChange = EditxyGridStpyChange
      OnKeyPress = PositiveKeyPress
    end
    object EditxyGridPosz: TEdit
      Left = 413
      Top = 51
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      OnChange = EditxyGridPoszChange
      OnKeyPress = FloatKeyPress
    end
    object xyLock: TCheckBox
      Left = 422
      Top = 93
      Width = 115
      Height = 30
      Cursor = crHandPoint
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = 'Lock x,y'
      Checked = True
      Font.Charset = ANSI_CHARSET
      Font.Color = clMaroon
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      State = cbChecked
      TabOrder = 7
      OnClick = xyLockClick
    end
  end
  object GroupBoxXZ: TGroupBox
    Left = 7
    Top = 147
    Width = 546
    Height = 142
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Anchors = [akTop, akRight]
    Caption = '  X, Z '#1088#1072#1084#1082#1080' '#1075#1088#1080#1076#1072
    ParentShowHint = False
    ShowHint = True
    TabOrder = 1
    object Label13: TLabel
      Left = 72
      Top = 26
      Width = 81
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = #1052#1080#1085#1080#1084#1091#1084
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label18: TLabel
      Left = 186
      Top = 26
      Width = 87
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = #1052#1072#1082#1089#1080#1084#1091#1084
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label20: TLabel
      Left = 291
      Top = 26
      Width = 96
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Alignment = taRightJustify
      Caption = #1048#1085#1082#1088#1077#1084#1077#1085#1090
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label21: TLabel
      Left = -4
      Top = 54
      Width = 36
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'x :'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label22: TLabel
      Left = -4
      Top = 93
      Width = 36
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'z :'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label23: TLabel
      Left = 424
      Top = 26
      Width = 116
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = #1055#1086#1079#1080#1094#1080#1103' ( y )'
    end
    object EditxzGridMinx: TEdit
      Left = 37
      Top = 51
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      OnChange = EditxzGridMinxChange
      OnKeyPress = FloatKeyPress
    end
    object EditxzGridMaxx: TEdit
      Left = 161
      Top = 51
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      OnChange = EditxzGridMaxxChange
      OnKeyPress = FloatKeyPress
    end
    object EditxzGridStpx: TEdit
      Left = 287
      Top = 51
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      OnChange = EditxzGridStpxChange
      OnExit = EditxzGridStpxExit
      OnKeyPress = PositiveKeyPress
    end
    object EditxzGridMinz: TEdit
      Left = 37
      Top = 89
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      OnChange = EditxzGridMinzChange
      OnKeyPress = FloatKeyPress
    end
    object EditxzGridMaxz: TEdit
      Left = 161
      Top = 89
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      OnChange = EditxzGridMaxzChange
      OnKeyPress = FloatKeyPress
    end
    object EditxzGridStpz: TEdit
      Left = 287
      Top = 89
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
      OnChange = EditxzGridStpzChange
      OnKeyPress = PositiveKeyPress
    end
    object EditxzGridPosy: TEdit
      Left = 413
      Top = 51
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      OnChange = EditxzGridPosyChange
      OnKeyPress = FloatKeyPress
    end
    object zLock: TCheckBox
      Left = 422
      Top = 98
      Width = 115
      Height = 30
      Cursor = crHandPoint
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = 'Lock z'
      Checked = True
      Font.Charset = ANSI_CHARSET
      Font.Color = clMaroon
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      State = cbChecked
      TabOrder = 7
      OnClick = zLockClick
    end
  end
  object GroupBoxYZ: TGroupBox
    Left = 7
    Top = 291
    Width = 546
    Height = 141
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Anchors = [akTop, akRight]
    Caption = '  Y, Z '#1088#1072#1084#1082#1080' '#1075#1088#1080#1076#1072
    ParentShowHint = False
    ShowHint = True
    TabOrder = 2
    object Label24: TLabel
      Left = 72
      Top = 26
      Width = 81
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = #1052#1080#1085#1080#1084#1091#1084
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label25: TLabel
      Left = 186
      Top = 26
      Width = 87
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = #1052#1072#1082#1089#1080#1084#1091#1084
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label26: TLabel
      Left = 291
      Top = 26
      Width = 96
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Alignment = taRightJustify
      Caption = #1048#1085#1082#1088#1077#1084#1077#1085#1090
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label27: TLabel
      Left = -2
      Top = 56
      Width = 35
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'y :'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label28: TLabel
      Left = -4
      Top = 93
      Width = 36
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Alignment = taRightJustify
      AutoSize = False
      Caption = 'z :'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Label29: TLabel
      Left = 424
      Top = 26
      Width = 116
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = #1055#1086#1079#1080#1094#1080#1103' ( x )'
    end
    object EdityzGridMiny: TEdit
      Left = 37
      Top = 51
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      OnChange = EdityzGridMinyChange
      OnKeyPress = FloatKeyPress
    end
    object EdityzGridMaxy: TEdit
      Left = 161
      Top = 51
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      OnChange = EdityzGridMaxyChange
      OnKeyPress = FloatKeyPress
    end
    object EdityzGridStpy: TEdit
      Left = 287
      Top = 51
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      OnChange = EdityzGridStpyChange
      OnExit = EdityzGridStpyExit
      OnKeyPress = PositiveKeyPress
    end
    object EdityzGridMinz: TEdit
      Left = 37
      Top = 89
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      OnChange = EdityzGridMinzChange
      OnKeyPress = FloatKeyPress
    end
    object EdityzGridMaxz: TEdit
      Left = 161
      Top = 89
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      OnChange = EdityzGridMaxzChange
      OnKeyPress = FloatKeyPress
    end
    object EdityzGridStpz: TEdit
      Left = 287
      Top = 89
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
      OnChange = EdityzGridStpzChange
      OnExit = EdityzGridStpzExit
      OnKeyPress = PositiveKeyPress
    end
    object EdityzGridPosx: TEdit
      Left = 413
      Top = 51
      Width = 128
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      OnChange = EdityzGridPosxChange
      OnKeyPress = FloatKeyPress
    end
    object MinLock: TCheckBox
      Left = 422
      Top = 93
      Width = 115
      Height = 30
      Cursor = crHandPoint
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = 'Minimum'
      Checked = True
      Font.Charset = ANSI_CHARSET
      Font.Color = clMaroon
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      State = cbChecked
      TabOrder = 7
      OnClick = MinLockClick
    end
  end
  object GroupBoxOp: TGroupBox
    Left = 7
    Top = 431
    Width = 546
    Height = 173
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Anchors = [akTop, akRight]
    Caption = '  '#1054#1087#1094#1080#1080
    ParentShowHint = False
    ShowHint = True
    TabOrder = 3
    object Label14: TLabel
      Left = 7
      Top = 26
      Width = 63
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      AutoSize = False
      Caption = 'Show :'
    end
    object Label19: TLabel
      Left = 334
      Top = 70
      Width = 109
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = 'View Depth :'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Colors: TSpeedButton
      Left = 301
      Top = 112
      Width = 95
      Height = 37
      Cursor = crHandPoint
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = '&'#1062#1074#1077#1090
      Flat = True
      Font.Charset = ANSI_CHARSET
      Font.Color = clMaroon
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      NumGlyphs = 2
      ParentFont = False
      OnClick = ColorsClick
    end
    object Label1: TLabel
      Left = 7
      Top = 70
      Width = 71
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = 'Scale z :'
    end
    object Centre: TSpeedButton
      Left = 156
      Top = 112
      Width = 136
      Height = 37
      Cursor = crHandPoint
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = 'Grids Centre '
      Flat = True
      Font.Charset = ANSI_CHARSET
      Font.Color = clMaroon
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      NumGlyphs = 2
      ParentFont = False
      OnClick = CentreClick
    end
    object Label4: TLabel
      Left = 170
      Top = 70
      Width = 83
      Height = 23
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = 'Box Line :'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object PlotValues: TSpeedButton
      Left = 12
      Top = 112
      Width = 130
      Height = 37
      Cursor = crHandPoint
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = 'Plot Values'
      Flat = True
      Font.Charset = ANSI_CHARSET
      Font.Color = clMaroon
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      NumGlyphs = 2
      ParentFont = False
      OnClick = PlotValuesClick
    end
    object xyGridCB: TCheckBox
      Left = 72
      Top = 25
      Width = 96
      Height = 29
      Cursor = crHandPoint
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = 'xy '#1075#1088#1080#1076
      TabOrder = 0
      OnClick = xyGridCBClick
    end
    object xzGridCB: TCheckBox
      Left = 182
      Top = 25
      Width = 96
      Height = 29
      Cursor = crHandPoint
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = 'xz '#1075#1088#1080#1076
      TabOrder = 1
      OnClick = xzGridCBClick
    end
    object yzGridCB: TCheckBox
      Left = 292
      Top = 25
      Width = 97
      Height = 29
      Cursor = crHandPoint
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = 'yz '#1075#1088#1080#1076
      TabOrder = 2
      OnClick = yzGridCBClick
    end
    object EditViewDepth: TEdit
      Left = 445
      Top = 65
      Width = 91
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
      Text = '10000'
      OnChange = EditViewDepthChange
      OnKeyPress = PositiveKeyPress
    end
    object EditzScale: TEdit
      Left = 82
      Top = 65
      Width = 79
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      OnKeyPress = PositiveKeyPress
      OnKeyUp = EditzScaleKeyUp
    end
    object BoxOutlineCB: TCheckBox
      Left = 403
      Top = 21
      Width = 133
      Height = 30
      Cursor = crHandPoint
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = #1082#1086#1085#1090#1077#1081#1085#1077#1088
      TabOrder = 3
      OnClick = BoxOutlineCBClick
    end
    object EditBoxLnWidth: TEdit
      Tag = 1
      Left = 254
      Top = 65
      Width = 75
      Height = 31
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
      OnKeyPress = IntKeyPress
      OnKeyUp = EditBoxLnWidthKeyUp
    end
    object BitBtn1: TBitBtn
      Left = 403
      Top = 107
      Width = 131
      Height = 51
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = '&'#1047#1072#1082#1088#1099#1090#1100
      Glyph.Data = {
        F6000000424DF600000000000000760000002800000010000000100000000100
        040000000000800000000000000000000000100000001000000000000000FFFF
        000000008400FF00FF0000FFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00330000000000
        0333330244444444033333022444444403333302224444440333330222044444
        0333330222044444033333022204444403333302220444440333330222044444
        0333330222044444033333022240444403333302220444440333330222044444
        0333330212044444033333021104444403333300000000000333}
      TabOrder = 7
      OnClick = BitBtn1Click
    end
  end
end
