object FormPosition: TFormPosition
  Left = 335
  Top = 113
  Margins.Left = 5
  Margins.Top = 5
  Margins.Right = 5
  Margins.Bottom = 5
  Caption = #1055#1086#1083#1086#1078#1077#1085#1080#1077
  ClientHeight = 903
  ClientWidth = 562
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -19
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  Position = poOwnerFormCenter
  OnShow = FormShow
  PixelsPerInch = 168
  TextHeight = 24
  object Panel2: TPanel
    Left = 0
    Top = 0
    Width = 562
    Height = 65
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    TabOrder = 9
    object Panel1: TPanel
      Left = 1
      Top = 1
      Width = 119
      Height = 63
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      BevelOuter = bvNone
      Caption = 'Creature:'
      TabOrder = 0
    end
    object panID: TPanel
      Left = 120
      Top = 1
      Width = 441
      Height = 63
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alClient
      Alignment = taLeftJustify
      BevelOuter = bvNone
      Caption = 'ID'
      TabOrder = 1
    end
  end
  object panButtonBar: TPanel
    Left = 0
    Top = 774
    Width = 562
    Height = 129
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alBottom
    BevelOuter = bvLowered
    TabOrder = 17
    object panOKButton: TPanel
      Left = 379
      Top = 1
      Width = 182
      Height = 127
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alRight
      BevelOuter = bvNone
      TabOrder = 0
      object btnOK: TBitBtn
        Left = 35
        Top = 74
        Width = 131
        Height = 43
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Kind = bkOK
        NumGlyphs = 2
        TabOrder = 0
        OnClick = btnOKClick
      end
    end
    object btnCancel: TBitBtn
      Left = 18
      Top = 74
      Width = 131
      Height = 43
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Kind = bkCancel
      NumGlyphs = 2
      TabOrder = 1
      OnClick = btnCancelClick
    end
    object btnApply: TBitBtn
      Left = 399
      Top = 18
      Width = 131
      Height = 43
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = 'Apply'
      TabOrder = 2
      OnClick = btnApplyClick
    end
    object btnCopy: TBitBtn
      Left = 18
      Top = 18
      Width = 131
      Height = 43
      Hint = 'Copy from another object'#39's position (enter handle).'
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Caption = 'Copy'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 3
      OnClick = btnCopyClick
    end
  end
  object Panel3: TPanel
    Left = 0
    Top = 65
    Width = 562
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 0
    object Panel4: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 40
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'X:'
      TabOrder = 0
    end
  end
  object Panel5: TPanel
    Left = 0
    Top = 628
    Width = 562
    Height = 41
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 14
    object Panel8: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 41
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'SizeX:'
      TabOrder = 0
    end
  end
  object Panel9: TPanel
    Left = 0
    Top = 588
    Width = 562
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 13
    object Panel10: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 40
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'Buoyancy:'
      TabOrder = 0
    end
  end
  object Panel11: TPanel
    Left = 0
    Top = 548
    Width = 562
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 12
    object Panel14: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 40
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'Bounce:'
      TabOrder = 0
    end
  end
  object Panel15: TPanel
    Left = 0
    Top = 508
    Width = 562
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 11
    object Panel16: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 40
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'Mass:'
      TabOrder = 0
    end
  end
  object Panel17: TPanel
    Left = 0
    Top = 467
    Width = 562
    Height = 41
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 10
    object Panel18: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 41
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'DirectionH:'
      TabOrder = 0
    end
  end
  object Panel19: TPanel
    Left = 0
    Top = 427
    Width = 562
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 18
    object Panel20: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 40
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'DirectionXY:'
      TabOrder = 0
    end
  end
  object Panel21: TPanel
    Left = 0
    Top = 387
    Width = 562
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 8
    object Panel22: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 40
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'Acceleration.H:'
      TabOrder = 0
    end
  end
  object Panel23: TPanel
    Left = 0
    Top = 347
    Width = 562
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 7
    object Panel24: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 40
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'Acceleration.Y:'
      TabOrder = 0
    end
  end
  object Panel25: TPanel
    Left = 0
    Top = 306
    Width = 562
    Height = 41
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 6
    object Panel26: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 41
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'Acceleration.X:'
      TabOrder = 0
    end
  end
  object Panel27: TPanel
    Left = 0
    Top = 266
    Width = 562
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 5
    object Panel28: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 40
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'Velocity.H:'
      TabOrder = 0
    end
  end
  object Panel29: TPanel
    Left = 0
    Top = 226
    Width = 562
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 4
    object Panel30: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 40
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'Velocity.Y:'
      TabOrder = 0
    end
  end
  object Panel31: TPanel
    Left = 0
    Top = 186
    Width = 562
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 3
    object Panel32: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 40
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'Velocity.X:'
      TabOrder = 0
    end
  end
  object Panel33: TPanel
    Left = 0
    Top = 145
    Width = 562
    Height = 41
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 2
    object Panel34: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 41
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'Height:'
      TabOrder = 0
    end
  end
  object Panel35: TPanel
    Left = 0
    Top = 105
    Width = 562
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 1
    object Panel36: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 40
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'Y:'
      TabOrder = 0
    end
  end
  object Panel41: TPanel
    Left = 0
    Top = 749
    Width = 562
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 19
    object Panel42: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 40
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'Tangible:'
      TabOrder = 0
    end
    object cbTangible: TCheckBox
      Left = 175
      Top = 7
      Width = 68
      Height = 30
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Enabled = False
      TabOrder = 2
    end
    object cbCollider: TCheckBox
      Left = 231
      Top = 7
      Width = 100
      Height = 30
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Alignment = taLeftJustify
      Caption = 'Collider:'
      Enabled = False
      TabOrder = 1
    end
  end
  object Panel43: TPanel
    Left = 0
    Top = 709
    Width = 562
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 16
    object Panel44: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 40
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'SizeH:'
      TabOrder = 0
    end
  end
  object Panel45: TPanel
    Left = 0
    Top = 669
    Width = 562
    Height = 40
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 15
    object Panel46: TPanel
      Left = 0
      Top = 0
      Width = 163
      Height = 40
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      Caption = 'SizeY:'
      TabOrder = 0
    end
  end
end
