object FormSatellite: TFormSatellite
  Left = 411
  Top = 200
  Margins.Left = 4
  Margins.Top = 4
  Margins.Right = 4
  Margins.Bottom = 4
  Caption = 'Satellite'
  ClientHeight = 606
  ClientWidth = 581
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -19
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  PixelsPerInch = 168
  TextHeight = 24
  object panDescription: TPanel
    Left = 0
    Top = 0
    Width = 581
    Height = 50
    Margins.Left = 6
    Margins.Top = 6
    Margins.Right = 6
    Margins.Bottom = 6
    Align = alTop
    BevelOuter = bvNone
    ParentColor = True
    TabOrder = 0
    object Label1: TLabel
      Left = 263
      Top = 14
      Width = 234
      Height = 24
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Caption = 'Intensity of effect per round,.'
    end
    object panRate: TPanel
      Left = 0
      Top = 0
      Width = 175
      Height = 50
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      BorderWidth = 5
      Caption = 'Rate:'
      ParentColor = True
      TabOrder = 0
    end
    object edRate: TEdit
      Left = 179
      Top = 7
      Width = 67
      Height = 32
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      TabOrder = 1
      Text = '1'
      OnChange = edRateChange
    end
  end
  object Panel1: TPanel
    Left = 0
    Top = 102
    Width = 581
    Height = 51
    Margins.Left = 6
    Margins.Top = 6
    Margins.Right = 6
    Margins.Bottom = 6
    Align = alTop
    BevelOuter = bvNone
    ParentColor = True
    TabOrder = 2
    object Label3: TLabel
      Left = 263
      Top = 14
      Width = 267
      Height = 24
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Caption = 'Rate of movement in clock ticks.'
    end
    object Panel2: TPanel
      Left = 0
      Top = 0
      Width = 175
      Height = 51
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      BorderWidth = 5
      Caption = 'Movement:'
      ParentColor = True
      TabOrder = 0
    end
    object edMovement: TEdit
      Left = 179
      Top = 7
      Width = 67
      Height = 32
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      TabOrder = 1
      Text = '25'
      OnChange = edMovementChange
    end
  end
  object Panel3: TPanel
    Left = 0
    Top = 50
    Width = 581
    Height = 52
    Margins.Left = 6
    Margins.Top = 6
    Margins.Right = 6
    Margins.Bottom = 6
    Align = alTop
    BevelOuter = bvNone
    ParentColor = True
    TabOrder = 1
    object Label2: TLabel
      Left = 263
      Top = 14
      Width = 146
      Height = 24
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Caption = 'Distance of effect.'
    end
    object Panel4: TPanel
      Left = 0
      Top = 0
      Width = 175
      Height = 52
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Align = alLeft
      Alignment = taRightJustify
      BevelOuter = bvNone
      BorderWidth = 5
      Caption = 'Radius:'
      ParentColor = True
      TabOrder = 0
    end
    object edRadius: TEdit
      Left = 179
      Top = 7
      Width = 67
      Height = 32
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      TabOrder = 1
      Text = '5'
      OnChange = edRadiusChange
    end
  end
  object Panel5: TPanel
    Left = 0
    Top = 153
    Width = 581
    Height = 133
    Margins.Left = 6
    Margins.Top = 6
    Margins.Right = 6
    Margins.Bottom = 6
    Align = alClient
    BevelOuter = bvNone
    BorderWidth = 5
    TabOrder = 3
    object rgDirection: TRadioGroup
      Left = 78
      Top = 5
      Width = 351
      Height = 123
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Align = alClient
      Caption = 'Direction:'
      Columns = 2
      ItemIndex = 2
      Items.Strings = (
        'Up'
        'Down'
        'Left'
        'Right')
      TabOrder = 0
      OnClick = rgDirectionClick
    end
    object Panel6: TPanel
      Left = 5
      Top = 5
      Width = 73
      Height = 123
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Align = alLeft
      BevelOuter = bvNone
      TabOrder = 1
    end
    object Panel7: TPanel
      Left = 429
      Top = 5
      Width = 147
      Height = 123
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Align = alRight
      BevelOuter = bvNone
      TabOrder = 2
    end
  end
  object panButtonBar: TPanel
    Left = 0
    Top = 533
    Width = 581
    Height = 73
    Margins.Left = 6
    Margins.Top = 6
    Margins.Right = 6
    Margins.Bottom = 6
    Align = alBottom
    BevelOuter = bvLowered
    TabOrder = 4
    object panOKButton: TPanel
      Left = 398
      Top = 1
      Width = 182
      Height = 71
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Align = alRight
      BevelOuter = bvNone
      TabOrder = 0
      object btnOK: TBitBtn
        Left = 18
        Top = 14
        Width = 130
        Height = 43
        Margins.Left = 6
        Margins.Top = 6
        Margins.Right = 6
        Margins.Bottom = 6
        Kind = bkOK
        NumGlyphs = 2
        TabOrder = 0
        OnClick = btnOKClick
      end
    end
  end
  object Panel8: TPanel
    Left = 0
    Top = 286
    Width = 581
    Height = 247
    Margins.Left = 6
    Margins.Top = 6
    Margins.Right = 6
    Margins.Bottom = 6
    Align = alBottom
    BevelOuter = bvNone
    TabOrder = 5
    object Label4: TLabel
      Left = 42
      Top = 28
      Width = 81
      Height = 24
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Caption = 'Epicenter'
    end
    object Label5: TLabel
      Left = 84
      Top = 70
      Width = 14
      Height = 24
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Caption = 'X'
    end
    object Label6: TLabel
      Left = 224
      Top = 70
      Width = 12
      Height = 24
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Caption = 'Y'
    end
    object Label7: TLabel
      Left = 378
      Top = 70
      Width = 12
      Height = 24
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Caption = 'Z'
    end
    object Label8: TLabel
      Left = 28
      Top = 140
      Width = 36
      Height = 24
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Caption = 'Size'
    end
    object Label9: TLabel
      Left = 28
      Top = 189
      Width = 72
      Height = 24
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Caption = 'Distance'
    end
    object edX: TEdit
      Left = 112
      Top = 56
      Width = 99
      Height = 32
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      TabOrder = 0
      Text = '0'
    end
    object edY: TEdit
      Left = 252
      Top = 56
      Width = 99
      Height = 32
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      TabOrder = 1
      Text = '0'
    end
    object edZ: TEdit
      Left = 406
      Top = 56
      Width = 99
      Height = 32
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      TabOrder = 2
      Text = '0'
    end
    object edSize: TEdit
      Left = 112
      Top = 126
      Width = 211
      Height = 32
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      TabOrder = 3
      Text = '2'
    end
    object edDistance: TEdit
      Left = 112
      Top = 175
      Width = 211
      Height = 32
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      TabOrder = 4
      Text = '5'
    end
  end
end
