object fbWorld: TfbWorld
  Left = 192
  Top = 200
  Margins.Left = 5
  Margins.Top = 5
  Margins.Right = 5
  Margins.Bottom = 5
  Caption = 'World'
  ClientHeight = 525
  ClientWidth = 936
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -19
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  PixelsPerInch = 168
  TextHeight = 24
  object Label1: TLabel
    Left = 98
    Top = 242
    Width = 97
    Height = 24
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Frequency:'
  end
  object Label2: TLabel
    Left = 98
    Top = 280
    Width = 73
    Height = 24
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Quantity:'
  end
  object Label4: TLabel
    Left = 21
    Top = 39
    Width = 123
    Height = 24
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Planet Settings'
  end
  object Label5: TLabel
    Left = 550
    Top = 84
    Width = 58
    Height = 24
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Radius'
  end
  object Label6: TLabel
    Left = 553
    Top = 126
    Width = 55
    Height = 24
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Height'
  end
  object Label7: TLabel
    Left = 560
    Top = 172
    Width = 48
    Height = 24
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Width'
  end
  object Label3: TLabel
    Left = 515
    Top = 39
    Width = 70
    Height = 24
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Statistics'
  end
  object Label8: TLabel
    Left = 88
    Top = 81
    Width = 56
    Height = 24
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Name:'
  end
  object Label9: TLabel
    Left = 77
    Top = 123
    Width = 66
    Height = 24
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Creator:'
  end
  object CheckBox1: TCheckBox
    Left = 67
    Top = 196
    Width = 274
    Height = 30
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Asteroid Showers'
    Checked = True
    State = cbChecked
    TabOrder = 0
  end
  object Edit1: TEdit
    Left = 196
    Top = 235
    Width = 79
    Height = 32
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    TabOrder = 1
    Text = '128'
  end
  object Edit2: TEdit
    Left = 196
    Top = 277
    Width = 79
    Height = 32
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    TabOrder = 2
    Text = '5'
  end
  object edRadius: TEdit
    Left = 623
    Top = 74
    Width = 75
    Height = 32
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    ReadOnly = True
    TabOrder = 3
    Text = '7'
  end
  object edHeight: TEdit
    Left = 623
    Top = 119
    Width = 79
    Height = 32
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    ReadOnly = True
    TabOrder = 4
    Text = '15'
  end
  object edWidth: TEdit
    Left = 623
    Top = 165
    Width = 79
    Height = 32
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    ReadOnly = True
    TabOrder = 5
    Text = '30'
  end
  object panButtonBar: TPanel
    Left = 0
    Top = 453
    Width = 936
    Height = 72
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alBottom
    BevelOuter = bvLowered
    TabOrder = 6
    object panOKButton: TPanel
      Left = 753
      Top = 1
      Width = 182
      Height = 70
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alRight
      BevelOuter = bvNone
      TabOrder = 0
      object btnOK: TBitBtn
        Left = 18
        Top = 14
        Width = 131
        Height = 44
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Kind = bkOK
        NumGlyphs = 2
        TabOrder = 0
      end
    end
  end
  object BitBtn1: TBitBtn
    Left = 46
    Top = 382
    Width = 288
    Height = 43
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Caption = 'Maximums'
    TabOrder = 7
  end
  object RichEdit1: TRichEdit
    Left = 515
    Top = 224
    Width = 411
    Height = 247
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    Lines.Strings = (
      'StatusReport')
    ParentFont = False
    TabOrder = 8
  end
  object Edit3: TEdit
    Left = 151
    Top = 74
    Width = 211
    Height = 32
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    TabOrder = 9
    Text = 'Biosphere'
  end
  object Edit4: TEdit
    Left = 151
    Top = 119
    Width = 211
    Height = 32
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    TabOrder = 10
    Text = 'user'
  end
end
